### ISSUE TITLE
bug: nvim/lua/utils.lua:78: attempt to index upvalue '_user_config' (a string value)

### ISSUE THREAD

**Issue by yangbin9317** [yetone/cosmos-nvim#10]
Hello yeston, thanks for your config, it helps a lot! 
Maybe we should give _user_config a default value instead of error string when config file is not exists.
nvim/lua/utils.lua:78: attempt to index upvalue '_user_config' (a string value)

https://github.com/yetone/cosmos-nvim/pull/9

**Comment by yetone** [comment]
Thank you for the fix!
