### ISSUE TITLE
color of startup background  does not match  

### ISSUE THREAD

**Issue by BilyZ98** [yetone/cosmos-nvim#12]
I'm trying to use this config on my mac. But the background color of the startup and the editing window does not match what is put in the README. 

Is anything wrong? How can I fix this? 

nvim version: 6.1
OS: mac
Thanks.

![image](https://user-images.githubusercontent.com/26542149/149615191-5465f615-4b32-4522-b064-2310d3166619.png)

![image](https://user-images.githubusercontent.com/26542149/149615255-fbdf40cf-0473-42d4-a016-bd51a89edcf2.png)

**Comment by yetone** [comment]
Which terminal emulator are you using? What is the value of your TERM environment variable?

echo $TERM

**Comment by BilyZ98** [comment]
I'm using zsh


Output of 
```
echo $TERM
```

is 
```
xterm-256color
```

**Comment by yetone** [comment]
Can you execute `:PackerSync`?

**Comment by BilyZ98** [comment]
I execute ``` :PackerSync ```

Here's screenshot 

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/26542149/149646505-c42b4738-72fb-4cc0-8109-be9590b557de.png">

**Comment by yetone** [comment]
The terminal emulator you are using should be the Terminal that comes with macos. [iTerm2](https://iterm2.com/) is highly recommended.

**Comment by BilyZ98** [comment]
I change the terminal emulator to iTerm2. Now the color looks fine.
Thanks.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/26542149/149646937-a1a90820-9f33-4e23-a809-536aa6b56f30.png">

**Comment by yetone** [comment]
@BilyZ98 You should install a nerd font to display the icons: https://github.com/yetone/cosmos-nvim#nerd-fonts

**Comment by BilyZ98** [comment]
@yetone  Thanks for your remind. 
iTerm2 comes with nerd front installed, so I change default font style to nerd font. 
Now I the icon in the start interface look exactly the same as you post. 
BTW, it feels good to edit with nvim with this config.


<img width="1050" alt="圖片" src="https://user-images.githubusercontent.com/26542149/149728990-87407a65-2a32-4b12-9f3f-8cde3b2e961d.png">
