### ISSUE TITLE
Another lsp progress plugin recommend

### ISSUE THREAD

**Issue by Junnplus** [yetone/cosmos-nvim#14]
Awesome repo!

I also used lualine-lsp-progress as the lsp status display before, but it relies on lualine.

I found another alternative -- fidge, standalone UI for nvim-lsp progress. https://github.com/j-hui/fidget.nvim

I think you might like it. Have a good weekend~

**Comment by yetone** [comment]
Awesome, looks like a great status display plugin! Thanks to the great Mr. Jun for the recommendation!

**Comment by jinzaizhichi** [comment]
What other dependencies do I need to install in advance according to your configuration?

**Comment by yetone** [comment]
Already added: https://github.com/yetone/cosmos-nvim/commit/846e9534b343abe291d6a1c04493eb94e2aff74f
