### ISSUE TITLE
leader key does not work on windows terminal 

### ISSUE THREAD

**Issue by BilyZ98** [yetone/cosmos-nvim#16]
I am using windows terminal and connecting to my centos server with this nvim config.
However the leader key \' \' is not working when I press space key. It does not prompt which key I can press next.

Edit: I think the reason space leader key does not work is because my os version is too low. Currently my server kernel version is 3.10 and the thing goes well when I use the same config on my unbuntu 18.10

**Comment by yetone** [comment]
@BilyZ98 Since I went back home to the countryside for the Lunar New Year, I apologize for the delay in my response. Has your problem been fixed?
