### ISSUE TITLE
Prompt the following error, how to solve, thank you!

### ISSUE THREAD

**Issue by jinzaizhichi** [yetone/cosmos-nvim#18]
packer.nvim: Error running config for bufferline.nvim: /home/jinzaizhichi/.config/nvim/lua/layers/ui/colors.lua:31: attempt to concatenate local 'theme' (a nil value)

**Comment by yetone** [comment]
Thanks for your report! I fixed it now: https://github.com/yetone/cosmos-nvim/commit/ad35ed545aa157599c66f8ffae46ba188c8389cc
