### ISSUE TITLE
[help wanted] How reduce the fuzzy prompt window background color opacity

### ISSUE THREAD

**Issue by yahaa** [yetone/cosmos-nvim#24]
Hi @yetone thanks your awesome config.
I  found that the background color of the prompt window is too transparent, such as the following screenshot

![image](https://user-images.githubusercontent.com/16364111/221246890-6d264aa5-5fbf-4777-9f3c-bb9c4cc037f9.png)

So there is a way to reduce the fuzzy prompt window background color opacity? Looking forward to your reply, thanks.

**Comment by yetone** [comment]
Thank you for using my configuration, you can change it with a user-defined configuration, the shortcut is <kbd>space</kbd>-<kbd>f</kbd>-<kbd>e</kbd>-<kbd>d</kbd>, and then add the `transparency` option on that layer of the `ui`, as shown in the following image:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/1206493/221249519-41921b85-ef91-4bca-bcb8-498c1655f6bb.png">

**Comment by yahaa** [comment]
Thanks.
