### ISSUE TITLE
Failed startup in Windows

### ISSUE THREAD

**Issue by riverscn** [yetone/cosmos-nvim#5]
![image](https://user-images.githubusercontent.com/555062/149168808-8df9885a-be3f-4df6-b0fe-64fdb80a8f62.png)

**Comment by yetone** [comment]
Thanks for the feedback, I'll test it on windows

Now can use docker to get a taste:

```bash
docker run -it -v $PWD:/code -w /code yetone/cosmosvim nvim
```

**Comment by yetone** [comment]
This bug should be fixed
