### ISSUE TITLE
font for correct display of all characters in status bar

### ISSUE THREAD

**Issue by jia2** [yetone/cosmos-nvim#6]
Can you please share with us which font I can use under Linux to get all characters in status bar correctly displayed?

![image](https://user-images.githubusercontent.com/3192880/149184938-72b2f8e9-59e2-4f05-a316-54e236e9ea75.png)

**Comment by yetone** [comment]
@jia2 https://www.nerdfonts.com/

**Comment by jia2** [comment]
Thanks a lot. :)
