### ISSUE TITLE
plugins download failed, how to download manually ?

### ISSUE THREAD

**Issue by BilyZ98** [yetone/cosmos-nvim#8]
Hi, I'm new to nvim and I am tryoing to use this config for my nvim but I failed download the required plugins.
When I restart nvim, it doesn't try to download plugins automatically. How can I fix this? 
Thanks.

**Comment by yetone** [comment]
`:PackerSync` will help you

**Comment by yetone** [comment]
or tap `<Space>-f-e-R`

**Comment by BilyZ98** [comment]
Edit:
For those who experience the same downloading plugins failed issue as me, I suggest that set up git config proxy to avoid this issue.
